#include "wifi_board.h"
#include "codecs/es8311_audio_codec.h"
#include "display/lcd_display.h"
#include "system_reset.h"
#include "application.h"
#include "button.h"
#include "config.h"
#include "device_state_event.h"
#include "user_avatar_sync.h"
#include <font_awesome.h>
#include <esp_log.h>
#include "i2c_device.h"
#include <driver/i2c_master.h>
#include <driver/ledc.h>
#include <wifi_station.h>
#include <esp_lcd_panel_vendor.h>
#include <esp_lcd_panel_io.h>
#include <esp_lcd_panel_ops.h>
#include <esp_timer.h>
#include "iot_button.h"
#include "power_manager.h"
#include "power_save_timer.h"
#include <sdkconfig.h>
#include <esp_app_desc.h>
#include <cmath>
#include <ctime>
#include <cstring>
#include <cstdio>
#include <cctype>
#include <array>
#include <string>

// Auto-generated by tmp/gen_firmware_assets.py — see avatar_assets.c
extern "C" const lv_img_dsc_t avatar_a;
extern "C" const lv_img_dsc_t bg_tile_4x4;

// Smaller CJK text font for badge layers — the global text font for this
// board is puhui_basic_20_4, which is too dense inside a 172 px badge.
// puhui_basic_16_4 is shipped by managed_components/78__xiaozhi-fonts but
// not used by default on the C6-1.69 board, so we extern-pull it in.
extern "C" const lv_font_t font_puhui_16_4;

#define TAG "waveshare_lcd_1_69"

#if CONFIG_IDF_TARGET_ESP32C6
constexpr bool kLightweightBadgeUi = true;
#else
constexpr bool kLightweightBadgeUi = false;
#endif

/* ─────────────────────────────────────────────────────────────────────
 * Hao Lab badge-watch layout for the Waveshare ESP32-C6-LCD-1.69 (240×280
 * native, rotated to 280×240 landscape).
 *
 * Mockup source-of-truth: tmp/badge-watch.html.
 *
 * Composition (outer rim inward):
 *   • cream surface + 4×4 ink grid bg (5 % opacity)
 *   • 60-tick dial: cardinal/major/minor backgrounds + clock/progress overlays
 *   • halo: always-on color circle behind the avatar, breathing intensity
 *   • central circular badge zone: 7 pre-built layers, swap by visibility
 *       1) avatar  2) boot  3) wifi-config  4) activating
 *       5) pairing 6) upgrading  7) error
 *   • 4 corner status slots: TL Wi-Fi (opacity steps), TR battery, BL/BR hidden
 *   • bottom ticker: static or marquee, role-driven content
 *
 * Implementation notes:
 *   - We keep base SpiLcdDisplay::SetupUI's widget tree intact (status_bar_,
 *     content_, emoji_box_, network_label_, etc.) so existing setter code
 *     keeps working. We re-parent / restyle / hide selectively.
 *   - State is driven by DeviceStateEventManager subscription bouncing into
 *     LVGL via lv_async_call. ApplyState() is the central dispatcher.
 *   - Override SetEmotion / SetChatMessage / UpdateStatusBar / SetPowerSaveMode
 *     to slice content into the appropriate layer without changing semantics.
 * ────────────────────────────────────────────────────────────────────── */
class CustomLcdDisplay : public SpiLcdDisplay {
public:
    CustomLcdDisplay(esp_lcd_panel_io_handle_t io_handle,
                    esp_lcd_panel_handle_t panel_handle,
                    int width,
                    int height,
                    int offset_x,
                    int offset_y,
                    bool mirror_x,
                    bool mirror_y,
                    bool swap_xy)
        : SpiLcdDisplay(io_handle, panel_handle,
                    width, height, offset_x, offset_y, mirror_x, mirror_y, swap_xy) {
        DisplayLockGuard lock(this);
        BuildBadgeLayout();
    }

    // ── Public overrides ─────────────────────────────────────────────
    // SetEmotion's job in the badge-watch UI is "pick a special-case badge
    // layer". Application::Alert() uses one of: "link" (pairing code),
    // "gear" (wifi config), "download" (OTA), "circle_xmark" (error). All
    // other emotions ("neutral" / "happy" / etc.) fall through and the
    // device-state callback decides the layer + halo.
    virtual void SetEmotion(const char* emotion) override {
        DisplayLockGuard lock(this);
        current_emotion_ = emotion ? emotion : "";
        if (current_emotion_ == "link") {
            ShowBadgeLayer(kBfPairing);
            UpdateHalo(COLOR_CORAL, 128, 242, 1800);
            SetDialMode(kDialOff);
        } else if (current_emotion_ == "gear") {
            ShowBadgeLayer(kBfWifi);
            UpdateHalo(COLOR_PEACH, 115, 204, 3000);
            SetDialMode(kDialOff);
        } else if (current_emotion_ == "download") {
            ShowBadgeLayer(kBfUpgrading);
            UpdateHalo(COLOR_PEACH, 140, 242, 1400);
            SetDialMode(kDialProgress);
        } else if (current_emotion_ == "circle_xmark") {
            ShowBadgeLayer(kBfError);
            UpdateHalo(COLOR_RED, 153, 255, 700);
            SetDialMode(kDialOff);
        }
        // For all other emotions: don't touch the badge layer; device-state
        // dispatcher owns it. Don't call base — base loads emoji glyphs/GIFs
        // into emoji_label_, which is permanently hidden in this layout.
    }

    // Replace the baked-in avatar_a on the badge avatar slot with a runtime
    // image (typically a PNG fetched by UserAvatarSync after OTA). We retain
    // ownership of the LvglImage so its underlying buffer outlives the
    // lv_image_dsc_t pointed at by lv_image_set_src.
    void SetUserAvatar(std::unique_ptr<LvglImage> image) override {
        if (!image || !image->image_dsc()) return;
        DisplayLockGuard lock(this);
        if (!bf_layers_[kBfAvatar]) return;
        lv_image_set_src(bf_layers_[kBfAvatar], image->image_dsc());
        lv_obj_center(bf_layers_[kBfAvatar]);
        user_avatar_image_ = std::move(image);
        const bool was_ready = user_avatar_ready_;
        user_avatar_ready_ = true;
        // If we were parked on the boot layer waiting for the avatar to
        // arrive (cache miss path), flip to the avatar layer now that we
        // have something real to show. ApplyState handles routing on every
        // other state transition.
        if (!was_ready &&
            (current_state_ == kDeviceStateIdle ||
             current_state_ == kDeviceStateConnecting ||
             current_state_ == kDeviceStateUnknown)) {
            ShowBadgeLayer(kBfAvatar);
        }
    }

    // Step 7: status-bar overlay. Base updates the network/battery glyphs;
    // we layer Cream-Cafe semantics on top:
    //   • Wi-Fi opacity → "off" / "config" / "on" tiers per device state
    //   • Battery low (≤QUARTER) tints the cell red + flips the bottom popup
    //     from a centered toast into a thin ticker-warning, and we engage
    //     the lowbat halo via ApplyState.
    virtual void UpdateStatusBar(bool update_all = false) override {
        SpiLcdDisplay::UpdateStatusBar(update_all);
        DisplayLockGuard lock(this);

        if (network_label_) {
            lv_opa_t op = LV_OPA_30;
            const auto state = current_state_;
            if (state == kDeviceStateWifiConfiguring) {
                op = LV_OPA_40;
            } else if (WifiStation::GetInstance().IsConnected()) {
                op = LV_OPA_COVER;
            }
            lv_obj_set_style_text_opa(network_label_, op, 0);
        }

        // Detect low battery from the icon pointer base just set.
        const bool low =
            battery_icon_ &&
            (std::strcmp(battery_icon_, FONT_AWESOME_BATTERY_EMPTY) == 0 ||
             std::strcmp(battery_icon_, FONT_AWESOME_BATTERY_QUARTER) == 0);
        if (battery_label_) {
            lv_obj_set_style_text_color(battery_label_,
                lv_color_hex(low ? COLOR_RED : COLOR_INK), 0);
        }
        if (low_battery_popup_ && low_battery_label_) {
            // Override the popup's default red bg/white text with a Cream-
            // Cafe friendly thin warning bar.
            lv_obj_set_style_bg_color(low_battery_popup_, lv_color_hex(COLOR_CREAM), 0);
            lv_obj_set_style_bg_opa(low_battery_popup_, LV_OPA_COVER, 0);
            lv_obj_set_style_border_color(low_battery_popup_, lv_color_hex(COLOR_RED), 0);
            lv_obj_set_style_border_width(low_battery_popup_, 1, 0);
            lv_obj_set_style_text_color(low_battery_label_, lv_color_hex(COLOR_RED), 0);
        }
        if (low_battery_active_ != low) {
            low_battery_active_ = low;
            // Re-dispatch the state so the halo flips to red (or restores).
            ApplyState(current_state_);
        }
    }

    // Step 8: power-save mode. Default base behavior is "show sleepy emoji",
    // but emoji_label_ is permanently hidden in this layout. Instead we
    // freeze the halo, kill the dial, and dim the ticker — gives a calm
    // "device sleeping" feel without flicker.
    virtual void SetPowerSaveMode(bool on) override {
        DisplayLockGuard lock(this);
        if (on) {
            FreezeHalo(LV_OPA_10);
            SetDialMode(kDialOff);
            if (chat_message_label_) {
                lv_obj_set_style_text_opa(chat_message_label_, LV_OPA_30, 0);
            }
        } else {
            if (chat_message_label_) {
                lv_obj_set_style_text_opa(chat_message_label_, LV_OPA_60, 0);
            }
            // Re-paint everything from current state — this restores the
            // halo animation, the dial mode, and any badge layer routing.
            ApplyState(current_state_);
        }
    }

    virtual void SetChatMessage(const char* role, const char* content) override {
        DisplayLockGuard lock(this);
        const std::string r = role ? role : "";
        const std::string c = content ? content : "";

        if (r == "system") {
            // Special-route by current emotion: parse the message into the
            // active bf-layer and DON'T update the ticker (ticker keeps
            // showing the version / state default chosen by ApplyState).
            if (current_emotion_ == "link") {
                std::string code = ExtractSixDigits(c);
                if (!code.empty() && bf_pairing_code_) {
                    lv_label_set_text(bf_pairing_code_, code.c_str());
                }
                return;
            }
            if (current_emotion_ == "gear") {
                std::string ap = ExtractAfter(c, "热点 ");
                std::string ip = ExtractIp(c);
                if (!ap.empty() && bf_wifi_ap_) lv_label_set_text(bf_wifi_ap_, ap.c_str());
                if (!ip.empty() && bf_wifi_ip_) lv_label_set_text(bf_wifi_ip_, ip.c_str());
                return;
            }
            if (current_emotion_ == "download") {
                int pct = -1;
                if (std::sscanf(c.c_str(), "%d%%", &pct) >= 1 && pct >= 0) {
                    char buf[16];
                    std::snprintf(buf, sizeof(buf), "%d%%", pct);
                    if (bf_upgrading_pct_) lv_label_set_text(bf_upgrading_pct_, buf);
                    UpdateProgress(pct);
                }
                if (bf_upgrading_size_) lv_label_set_text(bf_upgrading_size_, c.c_str());
                return;
            }
            if (current_emotion_ == "circle_xmark") {
                if (bf_error_text_ && !c.empty()) {
                    lv_label_set_text(bf_error_text_, c.c_str());
                }
                return;
            }
            // Default system message → ticker. During boot/setup phases
            // Application::Start pushes the user agent string here
            // ("waveshare-c6-lcd-1.69/1.0.2"); ignore it and keep the
            // current tagline. Empty content → version (post-dismiss /
            // post-channel-close cleanup).
            const bool boot_phase =
                current_state_ == kDeviceStateStarting ||
                current_state_ == kDeviceStateActivating ||
                current_state_ == kDeviceStateWifiConfiguring;
            if (boot_phase) return;
            SetTickerText(c.empty() ? AppVersionString() : c.c_str());
            return;
        }

        // user / assistant: live STT/TTS transcript. SetTickerText auto-
        // selects centered (short) vs left+marquee (long). Empty content
        // is a no-op so transient post-turn clears don't blank the strip.
        if (c.empty()) return;
        SetTickerText(c.c_str());
    }

private:
    // ── Tiny extractors used by SetChatMessage routing ────────────────
    static std::string ExtractSixDigits(const std::string& s) {
        for (size_t i = 0; i + 6 <= s.size(); ++i) {
            bool all = true;
            for (int j = 0; j < 6; ++j) {
                if (!std::isdigit(static_cast<unsigned char>(s[i + j]))) {
                    all = false;
                    break;
                }
            }
            if (all) {
                // Make sure surrounding chars aren't digits (avoid grabbing
                // 6 of a longer run by accident).
                bool left_ok  = (i == 0) || !std::isdigit(static_cast<unsigned char>(s[i - 1]));
                bool right_ok = (i + 6 == s.size()) ||
                                !std::isdigit(static_cast<unsigned char>(s[i + 6]));
                if (left_ok && right_ok) return s.substr(i, 6);
            }
        }
        return "";
    }

    // Read the token starting after `marker`, terminated by Chinese comma,
    // ASCII comma, space, or end of string.
    static std::string ExtractAfter(const std::string& s, const char* marker) {
        const auto p = s.find(marker);
        if (p == std::string::npos) return "";
        const auto start = p + std::strlen(marker);
        size_t end = start;
        while (end < s.size()) {
            const unsigned char ch = static_cast<unsigned char>(s[end]);
            // Chinese comma "，" is 3 bytes (0xEF 0xBC 0x8C); ascii ","; space; "\n".
            if (ch == ',' || ch == ' ' || ch == '\n' || ch == '\r') break;
            if (end + 2 < s.size() &&
                ch == 0xEF &&
                static_cast<unsigned char>(s[end + 1]) == 0xBC &&
                static_cast<unsigned char>(s[end + 2]) == 0x8C) break;
            ++end;
        }
        return s.substr(start, end - start);
    }

    // Pull a dotted IPv4 quad out of the message (handles plain IP or URL).
    static std::string ExtractIp(const std::string& s) {
        for (size_t i = 0; i < s.size(); ++i) {
            int a, b, c, d, n;
            if (std::sscanf(s.c_str() + i, "%d.%d.%d.%d%n", &a, &b, &c, &d, &n) == 4 &&
                a >= 0 && a <= 255 && b >= 0 && b <= 255 &&
                c >= 0 && c <= 255 && d >= 0 && d <= 255) {
                return s.substr(i, n);
            }
        }
        return "";
    }
    // ── Cream-cafe palette (matches tmp/badge-watch.html) ─────────────
    static constexpr uint32_t COLOR_CREAM       = 0xE8E1D3;
    static constexpr uint32_t COLOR_INK         = 0x1A1816;
    static constexpr uint32_t COLOR_CORAL       = 0xE8533A;
    static constexpr uint32_t COLOR_PEACH       = 0xF7CFB3;
    static constexpr uint32_t COLOR_SAGE        = 0x9BA27B;
    static constexpr uint32_t COLOR_RED         = 0xC8341A;
    static constexpr uint32_t COLOR_INK_FAINT   = 0xC9C2B5;  // ink @ ~22 % over cream

    // ── Geometry (landscape 280×240) ──────────────────────────────────
    static constexpr int BADGE_RADIUS = 86;
    static constexpr int RING_RADIUS  = 92;          // tick outer tip
    static constexpr int HALO_RADIUS  = 98;
    static constexpr int TICK_BG_LEN_CARDINAL = 6;
    static constexpr int TICK_BG_LEN_MAJOR    = 4;
    static constexpr int TICK_BG_LEN_MINOR    = 2;
    static constexpr int HOUR_MARK_W  = 4;
    static constexpr int HOUR_MARK_H  = 22;
    static constexpr int MINUTE_ARC_STROKE = 9;

    enum DialMode { kDialOff, kDialClock, kDialProgress };

    // Indices into bf_layers_; matches order in BuildBadgeLayers().
    enum BadgeLayer {
        kBfAvatar = 0,
        kBfBoot,
        kBfWifi,
        kBfActivating,
        kBfPairing,
        kBfUpgrading,
        kBfError,
        kBfCount
    };

    // ── State + widgets (populated by Build*) ─────────────────────────
    DeviceState current_state_ = kDeviceStateUnknown;
    DialMode    current_dial_mode_ = kDialOff;
    // Sentinel so the very first ShowBadgeLayer() call always toggles
    // visibility (defaults to a real layer would early-return and leave
    // the avatar — created visible during BuildBadgeLayers — leaking through).
    BadgeLayer  current_badge_layer_ = kBfCount;
    int         progress_pct_ = 0;
    bool        low_battery_active_ = false;

    // Dial overlays
    lv_obj_t*   hour_mark_   = nullptr;
    lv_obj_t*   minute_arc_  = nullptr;

    // Halo (single-color breathing circle)
    lv_obj_t*   halo_        = nullptr;
    lv_anim_t   halo_anim_;
    bool        halo_anim_running_ = false;

    // Pre-built badge layers — siblings inside emoji_box_
    std::array<lv_obj_t*, kBfCount> bf_layers_ = {};
    // Holds the LvglImage backing the avatar slot when SetUserAvatar is
    // active. Owning here keeps the decoded buffer alive for the lifetime
    // of the displayed lv_image; replacing the avatar releases the old one.
    std::unique_ptr<LvglImage> user_avatar_image_ = nullptr;
    // True once the slot points at the user's image (either rehydrated from
    // flash cache at boot or pushed by SetUserAvatar after a fresh download).
    // Gates the boot→avatar layer transition so we never flash the baked
    // default in between.
    bool user_avatar_ready_ = false;
    // Sub-widgets needed for runtime updates
    lv_obj_t*   bf_pairing_code_   = nullptr;
    lv_obj_t*   bf_upgrading_pct_  = nullptr;
    lv_obj_t*   bf_upgrading_size_ = nullptr;
    lv_obj_t*   bf_wifi_ap_   = nullptr;
    lv_obj_t*   bf_wifi_ip_   = nullptr;
    lv_obj_t*   bf_error_text_ = nullptr;

    // Periodic clock refresh (1-minute resolution)
    esp_timer_handle_t clock_timer_ = nullptr;

    // Last seen emotion string (drives bf-layer routing in SetChatMessage).
    std::string current_emotion_;

    // Center coords (resolved from runtime panel size in BuildBadgeLayout).
    int center_x_ = 0;
    int center_y_ = 0;

    // ── Build pipeline ────────────────────────────────────────────────
    void BuildBadgeLayout() {
        center_x_ = LV_HOR_RES / 2;
        // Pull the badge composition 8 px upward from geometric center so
        // the bottom-most cardinal tick clears the ticker line below.
        center_y_ = LV_VER_RES / 2 - 8;
        BuildBackground();
        BuildHalo();
        BuildDial();
        BuildBadgeLayers();
        BuildCorners();
        BuildTicker();
        StartClockTimer();

        // Initial paint. SetDeviceState(kDeviceStateStarting) fires from
        // Application::Start() shortly after we exit this constructor and
        // re-runs this dispatch via the event subscription below — but we
        // need a frame on screen during the gap.
        ApplyState(kDeviceStateStarting);

        DeviceStateEventManager::GetInstance().RegisterStateChangeCallback(
            [this](DeviceState /*prev*/, DeviceState curr) {
                struct AsyncCtx { CustomLcdDisplay* self; DeviceState s; };
                auto* ctx = new AsyncCtx{this, curr};
                lv_async_call([](void* arg) {
                    auto* c = static_cast<AsyncCtx*>(arg);
                    c->self->ApplyState(c->s);
                    delete c;
                }, ctx);
            });
    }

    // ── Layer 0: cream surface + grid texture ─────────────────────────
    void BuildBackground() {
        lv_obj_t* screen = lv_screen_active();
        lv_obj_set_style_bg_color(screen, lv_color_hex(COLOR_CREAM), 0);
        lv_obj_set_style_bg_opa(screen, LV_OPA_COVER, 0);
        lv_obj_set_style_bg_image_src(screen, &bg_tile_4x4, 0);
        lv_obj_set_style_bg_image_tiled(screen, true, 0);

        // Disable parent-built flex layouts so we can hand-place children.
        if (container_) {
            lv_obj_set_layout(container_, LV_LAYOUT_NONE);
            lv_obj_set_size(container_, LV_HOR_RES, LV_VER_RES);
            lv_obj_set_style_bg_opa(container_, LV_OPA_TRANSP, 0);
            lv_obj_set_style_border_opa(container_, LV_OPA_TRANSP, 0);
            lv_obj_set_style_pad_all(container_, 0, 0);
        }
        if (status_bar_) {
            lv_obj_set_size(status_bar_, 0, 0);
            lv_obj_set_style_bg_opa(status_bar_, LV_OPA_TRANSP, 0);
            lv_obj_set_style_border_opa(status_bar_, LV_OPA_TRANSP, 0);
            lv_obj_set_style_pad_all(status_bar_, 0, 0);
        }
        if (content_) {
            lv_obj_set_layout(content_, LV_LAYOUT_NONE);
            lv_obj_set_style_bg_opa(content_, LV_OPA_TRANSP, 0);
            lv_obj_set_style_border_opa(content_, LV_OPA_TRANSP, 0);
            lv_obj_set_style_pad_all(content_, 0, 0);
            lv_obj_set_size(content_, LV_HOR_RES, LV_VER_RES);
            lv_obj_set_pos(content_, 0, 0);
        }
        if (status_label_)       lv_obj_add_flag(status_label_, LV_OBJ_FLAG_HIDDEN);
        if (notification_label_) lv_obj_add_flag(notification_label_, LV_OBJ_FLAG_HIDDEN);
        if (version_label_)      lv_obj_add_flag(version_label_, LV_OBJ_FLAG_HIDDEN);
    }

    // ── Halo: solid color circle, behind ticks + avatar, with breathing opacity.
    // The HTML mockup uses a dual-radial gradient + blur — LVGL 9 has no native
    // multi-stop radial, so we approximate with a single-color filled circle
    // whose opacity oscillates between min and max. Color/period change per
    // device state. The tick ring + emoji_box_ paint on top, leaving a soft
    // 12-px annular glow visible around the avatar.
    void BuildHalo() {
        lv_obj_t* screen = lv_screen_active();
        halo_ = lv_obj_create(screen);
        lv_obj_remove_style_all(halo_);
        lv_obj_set_size(halo_, HALO_RADIUS * 2, HALO_RADIUS * 2);
        lv_obj_set_pos(halo_, center_x_ - HALO_RADIUS, center_y_ - HALO_RADIUS);
        lv_obj_set_style_radius(halo_, LV_RADIUS_CIRCLE, 0);
        lv_obj_set_style_bg_color(halo_, lv_color_hex(COLOR_INK), 0);
        lv_obj_set_style_bg_opa(halo_, LV_OPA_TRANSP, 0);
        lv_obj_set_style_border_opa(halo_, LV_OPA_TRANSP, 0);
        lv_obj_add_flag(halo_, LV_OBJ_FLAG_IGNORE_LAYOUT);
        // Push to bottom of screen's child list so dial ticks + avatar both
        // render above. lv_obj_move_background = "first child" = lowest z.
        lv_obj_move_background(halo_);
    }

    static void HaloOpaCb(void* var, int32_t value) {
        lv_obj_set_style_bg_opa(static_cast<lv_obj_t*>(var),
                                 static_cast<lv_opa_t>(value), 0);
    }

    // Re-parameterise the halo: color + breathing range + period.
    // Period is the full min→max→min cycle in ms.
    void UpdateHalo(uint32_t color, uint8_t opa_min, uint8_t opa_max,
                    uint32_t period_ms) {
        if (!halo_) return;
        lv_obj_set_style_bg_color(halo_, lv_color_hex(color), 0);
        lv_anim_delete(halo_, HaloOpaCb);

        if (kLightweightBadgeUi) {
            lv_obj_set_style_bg_opa(halo_, static_cast<lv_opa_t>((opa_min + opa_max) / 2), 0);
            halo_anim_running_ = false;
            return;
        }

        lv_anim_init(&halo_anim_);
        lv_anim_set_var(&halo_anim_, halo_);
        lv_anim_set_exec_cb(&halo_anim_, HaloOpaCb);
        lv_anim_set_values(&halo_anim_, opa_min, opa_max);
        lv_anim_set_time(&halo_anim_, period_ms / 2);
        lv_anim_set_playback_time(&halo_anim_, period_ms / 2);
        lv_anim_set_repeat_count(&halo_anim_, LV_ANIM_REPEAT_INFINITE);
        lv_anim_set_path_cb(&halo_anim_, lv_anim_path_ease_in_out);
        lv_anim_start(&halo_anim_);
        halo_anim_running_ = true;
    }

    // Freeze the halo at a fixed opacity (used for power-save mode).
    void FreezeHalo(uint8_t opa) {
        if (!halo_) return;
        lv_anim_delete(halo_, HaloOpaCb);
        lv_obj_set_style_bg_opa(halo_, opa, 0);
        halo_anim_running_ = false;
    }

    // ── Dial: 60 background ticks (cardinal/major/minor) ──────────────
    void BuildDial() {
        lv_obj_t* screen = lv_screen_active();
        for (int i = 0; i < 60; i++) {
            const bool is_cardinal = (i % 15 == 0);
            const bool is_major    = (i % 5 == 0);
            const int  len = is_cardinal ? TICK_BG_LEN_CARDINAL
                           : is_major    ? TICK_BG_LEN_MAJOR
                                         : TICK_BG_LEN_MINOR;
            const int  w   = is_cardinal ? 2 : 1;
            const lv_opa_t opa = is_cardinal ? LV_OPA_70
                              : is_major    ? LV_OPA_40
                                            : LV_OPA_30;

            const float ang = (i * 6.0f) * (3.14159265f / 180.0f);
            const float sx = sinf(ang), cx = cosf(ang);
            const int outer_x = center_x_ + (int)(sx * RING_RADIUS);
            const int outer_y = center_y_ - (int)(cx * RING_RADIUS);
            const int inner_x = center_x_ + (int)(sx * (RING_RADIUS - len));
            const int inner_y = center_y_ - (int)(cx * (RING_RADIUS - len));
            const int mx = (outer_x + inner_x) / 2;
            const int my = (outer_y + inner_y) / 2;

            lv_obj_t* t = lv_obj_create(screen);
            lv_obj_remove_style_all(t);
            lv_obj_set_size(t, w, len);
            lv_obj_set_style_bg_color(t, lv_color_hex(COLOR_INK), 0);
            lv_obj_set_style_bg_opa(t, opa, 0);
            lv_obj_set_style_radius(t, 0, 0);
            lv_obj_set_style_transform_angle(t, i * 60, 0);
            lv_obj_set_style_transform_pivot_x(t, w / 2, 0);
            lv_obj_set_style_transform_pivot_y(t, len / 2, 0);
            lv_obj_set_pos(t, mx - w / 2, my - len / 2);
            lv_obj_add_flag(t, LV_OBJ_FLAG_IGNORE_LAYOUT);
        }

        // ── minute_arc_: single peach arc, doubles for clock + progress ──
        // Sized to outer radius RING_RADIUS so its stroke lands in the same
        // band as the tick ring (r ≈ 88..92). emoji_box_ (re-parented later
        // in BuildBadgeLayers) is appended after this widget, so it sits on
        // top and clips the inner half — only the 4 px in the tick zone shows.
        minute_arc_ = lv_arc_create(screen);
        lv_obj_remove_style(minute_arc_, nullptr, LV_PART_KNOB);
        lv_obj_set_size(minute_arc_, RING_RADIUS * 2, RING_RADIUS * 2);
        lv_obj_set_pos(minute_arc_, center_x_ - RING_RADIUS, center_y_ - RING_RADIUS);
        lv_arc_set_rotation(minute_arc_, 270);   // 0° = 12 o'clock
        lv_arc_set_bg_angles(minute_arc_, 0, 360);
        lv_arc_set_angles(minute_arc_, 0, 0);
        lv_obj_set_style_arc_color(minute_arc_, lv_color_hex(COLOR_PEACH), LV_PART_INDICATOR);
        lv_obj_set_style_arc_opa(minute_arc_, LV_OPA_COVER, LV_PART_INDICATOR);
        lv_obj_set_style_arc_width(minute_arc_, 4, LV_PART_INDICATOR);
        lv_obj_set_style_arc_opa(minute_arc_, LV_OPA_TRANSP, LV_PART_MAIN);
        lv_obj_set_style_arc_width(minute_arc_, 0, LV_PART_MAIN);
        lv_obj_set_style_bg_opa(minute_arc_, LV_OPA_TRANSP, 0);
        lv_obj_set_style_border_opa(minute_arc_, LV_OPA_TRANSP, 0);
        lv_obj_clear_flag(minute_arc_, LV_OBJ_FLAG_CLICKABLE);
        lv_obj_add_flag(minute_arc_, LV_OBJ_FLAG_IGNORE_LAYOUT);
        lv_obj_add_flag(minute_arc_, LV_OBJ_FLAG_HIDDEN);

        // ── hour_mark_: coral bar at radius ~89, repositioned per minute ──
        hour_mark_ = lv_obj_create(screen);
        lv_obj_remove_style_all(hour_mark_);
        lv_obj_set_size(hour_mark_, HOUR_MARK_W, HOUR_MARK_H);
        lv_obj_set_style_radius(hour_mark_, 1, 0);
        lv_obj_set_style_bg_color(hour_mark_, lv_color_hex(COLOR_CORAL), 0);
        lv_obj_set_style_bg_opa(hour_mark_, LV_OPA_COVER, 0);
        lv_obj_add_flag(hour_mark_, LV_OBJ_FLAG_IGNORE_LAYOUT);
        lv_obj_add_flag(hour_mark_, LV_OBJ_FLAG_HIDDEN);
    }

    // Reposition the hour_mark_ rectangle so its center sits at the angle
    // matching the current local time. Angle is measured clockwise from 12 o'clock.
    void UpdateHourMark(int hour, int minute) {
        if (!hour_mark_) return;
        // Each hour spans 30° (12 hours = 360°). Plus minute interpolation.
        const float deg = ((hour % 12) + minute / 60.0f) * 30.0f;
        const float rad = deg * 3.14159265f / 180.0f;
        const float sx = sinf(rad), cx = cosf(rad);
        // Place center at radius (RING_RADIUS - HOUR_MARK_H/2) so the outer
        // edge sits flush with the dial and the inner edge dives into the
        // avatar zone (where it gets clipped by emoji_box_ on top).
        const int r = RING_RADIUS - HOUR_MARK_H / 2;
        const int mx = center_x_ + (int)(sx * r);
        const int my = center_y_ - (int)(cx * r);
        lv_obj_set_pos(hour_mark_, mx - HOUR_MARK_W / 2, my - HOUR_MARK_H / 2);
        // 0.1° units; rotate around the rectangle's own center.
        lv_obj_set_style_transform_pivot_x(hour_mark_, HOUR_MARK_W / 2, 0);
        lv_obj_set_style_transform_pivot_y(hour_mark_, HOUR_MARK_H / 2, 0);
        lv_obj_set_style_transform_angle(hour_mark_, (int32_t)(deg * 10.0f), 0);
    }

    // Switch dial overlays per state.
    void SetDialMode(DialMode mode) {
        current_dial_mode_ = mode;
        if (mode == kDialOff) {
            if (minute_arc_) lv_obj_add_flag(minute_arc_, LV_OBJ_FLAG_HIDDEN);
            if (hour_mark_)  lv_obj_add_flag(hour_mark_,  LV_OBJ_FLAG_HIDDEN);
            return;
        }
        if (mode == kDialClock) {
            // Peach minute fill + coral hour bar.
            if (minute_arc_) {
                lv_obj_set_style_arc_color(minute_arc_, lv_color_hex(COLOR_PEACH),
                                             LV_PART_INDICATOR);
                lv_obj_clear_flag(minute_arc_, LV_OBJ_FLAG_HIDDEN);
            }
            if (hour_mark_) lv_obj_clear_flag(hour_mark_, LV_OBJ_FLAG_HIDDEN);
            RefreshClock();
            return;
        }
        // kDialProgress
        if (minute_arc_) {
            lv_obj_set_style_arc_color(minute_arc_, lv_color_hex(COLOR_CORAL),
                                         LV_PART_INDICATOR);
            lv_obj_clear_flag(minute_arc_, LV_OBJ_FLAG_HIDDEN);
        }
        if (hour_mark_) lv_obj_add_flag(hour_mark_, LV_OBJ_FLAG_HIDDEN);
        UpdateProgress(progress_pct_);
    }

    // Read system clock and snap minute_arc_ + hour_mark_ to wall-time.
    // No-op until SNTP has set system time (year >= 2025).
    void RefreshClock() {
        if (current_dial_mode_ != kDialClock) return;
        time_t now = time(nullptr);
        struct tm tm_local;
        localtime_r(&now, &tm_local);
        if (tm_local.tm_year < 2025 - 1900) {
            // Time not yet set — show empty dial (no fill, hour mark at 12).
            if (minute_arc_) lv_arc_set_angles(minute_arc_, 0, 0);
            UpdateHourMark(0, 0);
            return;
        }
        if (minute_arc_) {
            lv_arc_set_angles(minute_arc_, 0, tm_local.tm_min * 6);
        }
        UpdateHourMark(tm_local.tm_hour, tm_local.tm_min);
    }

    // Drive the progress arc from upgrade-percent (0..100).
    void UpdateProgress(int pct) {
        progress_pct_ = pct < 0 ? 0 : (pct > 100 ? 100 : pct);
        if (current_dial_mode_ == kDialProgress && minute_arc_) {
            lv_arc_set_angles(minute_arc_, 0, (int32_t)(progress_pct_ * 3.6f));
        }
    }

    // ── Central badge: cream circle + 7 pre-built layers ──────────────
    void BuildBadgeLayers() {
        lv_obj_t* screen = lv_screen_active();
        if (emoji_box_) {
            lv_obj_set_parent(emoji_box_, screen);
            lv_obj_set_size(emoji_box_, BADGE_RADIUS * 2, BADGE_RADIUS * 2);
            lv_obj_set_style_radius(emoji_box_, LV_RADIUS_CIRCLE, 0);
            lv_obj_set_style_bg_color(emoji_box_, lv_color_hex(COLOR_CREAM), 0);
            lv_obj_set_style_bg_opa(emoji_box_, LV_OPA_COVER, 0);
            // No hairline ring around the avatar — the breathing halo IS the
            // outer ring. Border kept transparent on every side.
            lv_obj_set_style_border_opa(emoji_box_, LV_OPA_TRANSP, 0);
            lv_obj_set_style_border_width(emoji_box_, 0, 0);
            lv_obj_set_style_clip_corner(emoji_box_, true, 0);
            lv_obj_set_pos(emoji_box_, center_x_ - BADGE_RADIUS, center_y_ - BADGE_RADIUS);
            lv_obj_add_flag(emoji_box_, LV_OBJ_FLAG_IGNORE_LAYOUT);
            // Children are scroll-disabled — content fits, no scroll desired.
            lv_obj_clear_flag(emoji_box_, LV_OBJ_FLAG_SCROLLABLE);
        }
        if (emoji_label_) {
            lv_obj_set_style_text_color(emoji_label_, lv_color_hex(COLOR_INK), 0);
            lv_obj_center(emoji_label_);
            lv_obj_add_flag(emoji_label_, LV_OBJ_FLAG_HIDDEN);
        }
        if (!emoji_box_) return;

        // ── Layer 0: avatar (default visible) ─────────────────────────
        // Try the persisted user avatar first — if flash has it, we render
        // the user's image from the very first paint. Cache miss falls back
        // to the baked `avatar_a` (cream-cafe cat) until the OTA-driven
        // download completes.
        {
            lv_obj_t* avatar = lv_image_create(emoji_box_);
            auto cached = UserAvatarSync::LoadCachedImage();
            if (cached) {
                lv_image_set_src(avatar, cached->image_dsc());
                user_avatar_image_ = std::move(cached);
                user_avatar_ready_ = true;
            } else {
                lv_image_set_src(avatar, &avatar_a);
            }
            lv_obj_center(avatar);
            bf_layers_[kBfAvatar] = avatar;
        }

        // Helper: make a flex-column layer that fills emoji_box_, hidden by default.
        auto make_layer = [&](BadgeLayer idx, int row_pad) -> lv_obj_t* {
            lv_obj_t* layer = lv_obj_create(emoji_box_);
            lv_obj_remove_style_all(layer);
            lv_obj_set_size(layer, BADGE_RADIUS * 2, BADGE_RADIUS * 2);
            lv_obj_set_pos(layer, 0, 0);
            lv_obj_set_flex_flow(layer, LV_FLEX_FLOW_COLUMN);
            lv_obj_set_flex_align(layer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                                   LV_FLEX_ALIGN_CENTER);
            lv_obj_set_style_pad_all(layer, 8, 0);
            lv_obj_set_style_pad_row(layer, row_pad, 0);
            lv_obj_clear_flag(layer, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_add_flag(layer, LV_OBJ_FLAG_HIDDEN);
            bf_layers_[idx] = layer;
            return layer;
        };

        // Helper: text label child with font + color + opacity.
        // When `font == nullptr` we fall back to the smaller 16 pt CJK
        // font (instead of inheriting the screen's 20 pt global) so badge
        // text fits comfortably inside the 172 px circle.
        auto add_label = [](lv_obj_t* parent, const char* text,
                             const lv_font_t* font, uint32_t color, lv_opa_t opa) -> lv_obj_t* {
            lv_obj_t* lbl = lv_label_create(parent);
            lv_label_set_text(lbl, text);
            lv_obj_set_style_text_font(lbl, font ? font : &font_puhui_16_4, 0);
            lv_obj_set_style_text_color(lbl, lv_color_hex(color), 0);
            lv_obj_set_style_text_opa(lbl, opa, 0);
            lv_obj_set_style_text_align(lbl, LV_TEXT_ALIGN_CENTER, 0);
            return lbl;
        };

        // Helper: spinner (1.2 s rotation, coral arc) sized to 26 px.
        auto add_spinner = [](lv_obj_t* parent) -> lv_obj_t* {
            if (kLightweightBadgeUi) {
                lv_obj_t* s = lv_label_create(parent);
                lv_label_set_text(s, "...");
                lv_obj_set_style_text_font(s, &lv_font_montserrat_28, 0);
                lv_obj_set_style_text_color(s, lv_color_hex(COLOR_CORAL), 0);
                return s;
            }

            lv_obj_t* s = lv_spinner_create(parent);
            lv_obj_set_size(s, 26, 26);
            lv_spinner_set_anim_params(s, 1200, 60);
            lv_obj_set_style_arc_color(s, lv_color_hex(COLOR_INK_FAINT),
                                        LV_PART_MAIN);
            lv_obj_set_style_arc_color(s, lv_color_hex(COLOR_CORAL),
                                        LV_PART_INDICATOR);
            lv_obj_set_style_arc_width(s, 3, LV_PART_MAIN);
            lv_obj_set_style_arc_width(s, 3, LV_PART_INDICATOR);
            return s;
        };

        // ── Layer 1: boot ─────────────────────────────────────────────
        // Spinner above + "启动中" below. Acts as both the startup screen
        // and the avatar-not-yet-cached holding screen (UserAvatarSync
        // parks here until SetUserAvatar fires for cache-miss boots).
        {
            lv_obj_t* l = make_layer(kBfBoot, 8);
            add_spinner(l);
            add_label(l, "启动中", nullptr, COLOR_INK, LV_OPA_COVER);
        }

        // ── Layer 2: wifi-config (2 lines) ────────────────────────────
        // Phone OSes auto-pop the captive-portal page after joining the AP,
        // so we don't need to instruct the user to open 192.168.4.1 manually.
        {
            lv_obj_t* l = make_layer(kBfWifi, 6);
            add_label(l, "手机 Wi-Fi 搜索连接", nullptr, COLOR_INK, LV_OPA_70);
            // AP name placeholder — populated at runtime by SetChatMessage.
            bf_wifi_ap_ = add_label(l, "HaoLab-XXXX", nullptr, COLOR_CORAL, LV_OPA_COVER);
            // bf_wifi_ip_ kept as nullptr; SetChatMessage's IP write is a no-op.
        }

        // ── Layer 3: activating ───────────────────────────────────────
        {
            lv_obj_t* l = make_layer(kBfActivating, 6);
            add_spinner(l);
            add_label(l, "激活中", nullptr, COLOR_INK, LV_OPA_COVER);
        }

        // ── Layer 4: pairing code ─────────────────────────────────────
        {
            lv_obj_t* l = make_layer(kBfPairing, 4);
            add_label(l, "配对码", nullptr, COLOR_INK, LV_OPA_60);
            bf_pairing_code_ = add_label(l, "------", &lv_font_montserrat_28,
                                          COLOR_CORAL, LV_OPA_COVER);
            add_label(l, "在平台输入", nullptr, COLOR_INK, LV_OPA_60);
        }

        // ── Layer 5: upgrading ────────────────────────────────────────
        {
            lv_obj_t* l = make_layer(kBfUpgrading, 4);
            bf_upgrading_pct_ = add_label(l, "0%", &lv_font_montserrat_36,
                                            COLOR_CORAL, LV_OPA_COVER);
            add_label(l, "固件升级中", nullptr, COLOR_INK, LV_OPA_COVER);
            bf_upgrading_size_ = add_label(l, "", nullptr, COLOR_INK, LV_OPA_60);
        }

        // ── Layer 6: error ────────────────────────────────────────────
        {
            lv_obj_t* l = make_layer(kBfError, 4);
            add_label(l, "!", &lv_font_montserrat_44, COLOR_CORAL, LV_OPA_COVER);
            bf_error_text_ = add_label(l, "出错了", nullptr, COLOR_INK, LV_OPA_COVER);
            add_label(l, "稍后重试", nullptr, COLOR_INK, LV_OPA_60);
        }
    }

    // ── Toggle the visible layer; cheap because all layers are pre-built.
    void ShowBadgeLayer(BadgeLayer idx) {
        if (idx == current_badge_layer_) return;
        for (int i = 0; i < kBfCount; ++i) {
            if (!bf_layers_[i]) continue;
            if (i == static_cast<int>(idx)) {
                lv_obj_clear_flag(bf_layers_[i], LV_OBJ_FLAG_HIDDEN);
            } else {
                lv_obj_add_flag(bf_layers_[i], LV_OBJ_FLAG_HIDDEN);
            }
        }
        current_badge_layer_ = idx;
    }

    // ── 4-corner status icons ─────────────────────────────────────────
    // Margins: 16 px from edges. The Waveshare module case covers ~6–8 px
    // of the LCD perimeter, so anything tighter than 14 sits visibly under
    // the bezel.
    void BuildCorners() {
        lv_obj_t* screen = lv_screen_active();
        if (network_label_) {
            lv_obj_set_parent(network_label_, screen);
            lv_obj_set_style_text_color(network_label_, lv_color_hex(COLOR_INK), 0);
            lv_obj_align(network_label_, LV_ALIGN_TOP_LEFT, 16, 14);
        }
        if (battery_label_) {
            lv_obj_set_parent(battery_label_, screen);
            lv_obj_set_style_text_color(battery_label_, lv_color_hex(COLOR_INK), 0);
            lv_obj_align(battery_label_, LV_ALIGN_TOP_RIGHT, -16, 14);
        }
        if (mute_label_) {
            lv_obj_set_parent(mute_label_, screen);
            lv_obj_set_style_text_color(mute_label_, lv_color_hex(COLOR_INK), 0);
            lv_obj_align(mute_label_, LV_ALIGN_TOP_LEFT, 38, 14);
        }
        if (low_battery_popup_) {
            lv_obj_align(low_battery_popup_, LV_ALIGN_BOTTOM_MID, 0, -22);
        }
    }

    // ── Bottom ticker (chat_message_label_ in marquee mode) ───────────
    void BuildTicker() {
        if (!chat_message_label_) return;
        lv_obj_set_parent(chat_message_label_, lv_screen_active());
        lv_label_set_long_mode(chat_message_label_, LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_obj_set_width(chat_message_label_, LV_HOR_RES - 32);
        lv_obj_set_style_text_align(chat_message_label_, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(chat_message_label_, lv_color_hex(COLOR_INK), 0);
        lv_obj_set_style_text_opa(chat_message_label_, LV_OPA_60, 0);
        lv_obj_set_style_text_font(chat_message_label_, &font_puhui_16_4, 0);
        // 8 px from the bottom edge. Combined with the 8 px upward shift of
        // the dial above, this gives the ticker label ~6 px clearance from
        // the bottommost cardinal tick.
        lv_obj_align(chat_message_label_, LV_ALIGN_BOTTOM_MID, 0, -8);
    }

    // ── Periodic refresh for clock-mode dial (1-minute resolution) ────
    void StartClockTimer() {
        const esp_timer_create_args_t args = {
            .callback = [](void* arg) {
                lv_async_call([](void* a) {
                    static_cast<CustomLcdDisplay*>(a)->RefreshClock();
                }, arg);
            },
            .arg = this,
            .dispatch_method = ESP_TIMER_TASK,
            .name = "haolab_clock",
            .skip_unhandled_events = true,
        };
        ESP_ERROR_CHECK(esp_timer_create(&args, &clock_timer_));
        ESP_ERROR_CHECK(esp_timer_start_periodic(clock_timer_, 60ULL * 1000 * 1000));
    }

    // ── Ticker convenience (auto-fit: center if it fits, scroll if not) ─
    // Measures the rendered width of `text` against the ticker's content
    // width (LV_HOR_RES - 32). Fits → DOT mode + CENTER align (static,
    // visually balanced). Doesn't fit → SCROLL_CIRCULAR + LEFT align
    // (LVGL only scrolls non-CENTER text). Width is re-asserted every
    // call in case some upstream layout pass clobbered it.
    void SetTickerText(const char* text) {
        if (!chat_message_label_) return;
        const char* s = text ? text : "";
        const int32_t max_w = LV_HOR_RES - 32;

        if (kLightweightBadgeUi) {
            lv_obj_set_width(chat_message_label_, max_w);
            lv_label_set_long_mode(chat_message_label_, LV_LABEL_LONG_DOT);
            lv_obj_set_style_text_align(chat_message_label_, LV_TEXT_ALIGN_CENTER, 0);
            lv_label_set_text(chat_message_label_, s);
            return;
        }

        lv_point_t size = {0, 0};
        if (*s) {
            lv_text_get_size(&size, s, &font_puhui_16_4, 0, 0,
                              LV_COORD_MAX, LV_TEXT_FLAG_NONE);
        }
        const bool fits = size.x <= max_w;
        lv_obj_set_width(chat_message_label_, max_w);
        lv_label_set_long_mode(chat_message_label_,
            fits ? LV_LABEL_LONG_DOT : LV_LABEL_LONG_SCROLL_CIRCULAR);
        lv_obj_set_style_text_align(chat_message_label_,
            fits ? LV_TEXT_ALIGN_CENTER : LV_TEXT_ALIGN_LEFT, 0);
        lv_label_set_text(chat_message_label_, s);
    }

    // App version string ("v1.0.2 by Hao Lab") cached after first call.
    // Always-on bottom-line tagline when the ticker has nothing else to say
    // (idle, listening before STT, speaking before TTS).
    const char* AppVersionString() {
        // "v" + version[32] + " by Hao Lab" + null.
        static char ver_str[56] = {0};
        if (ver_str[0] == 0) {
            const esp_app_desc_t* desc = esp_app_get_description();
            if (desc) snprintf(ver_str, sizeof(ver_str), "v%s by Hao Lab", desc->version);
            else      std::strcpy(ver_str, "v? by Hao Lab");
        }
        return ver_str;
    }

    // ── Central state → UI dispatcher ────────────────────────────────
    // Called from device-state events (lv_async bounce, LVGL task) and
    // from the constructor as an initial paint. Other overrides
    // (SetEmotion / SetChatMessage) may have already routed the badge
    // layer to a more specific view (pairing / upgrading / error /
    // wifi-config); we respect that override unless the new state moves
    // out of its parent state (e.g. Activating → Idle clears pairing).
    void ApplyState(DeviceState state) {
        DisplayLockGuard lock(this);
        const DeviceState prev = current_state_;
        current_state_ = state;

        // When stepping out of an emotion-driven override layer (pairing /
        // upgrading / error), invalidate the cached current_badge_layer_ so
        // the ShowBadgeLayer() call later in this dispatch actually executes
        // its hide/show toggle. Setting it to the *target* layer would make
        // ShowBadgeLayer's `idx == current_badge_layer_` short-circuit fire,
        // leaving the override layer visible (the bug that kept the pairing
        // screen on after server confirmed bound).
        if (prev != state) {
            const bool leaving_activating = (prev == kDeviceStateActivating);
            const bool leaving_upgrading  = (prev == kDeviceStateUpgrading);
            if ((leaving_activating && current_badge_layer_ == kBfPairing) ||
                (leaving_upgrading  && current_badge_layer_ == kBfUpgrading) ||
                (current_badge_layer_ == kBfError && state != kDeviceStateUnknown)) {
                current_badge_layer_ = kBfCount;   // sentinel — forces re-toggle
            }
        }

        switch (state) {
            case kDeviceStateStarting:
                ShowBadgeLayer(kBfBoot);
                UpdateHalo(COLOR_PEACH, 102, 191, 2600);   // 40 → 75 %
                SetDialMode(kDialOff);
                SetTickerText(AppVersionString());
                break;
            case kDeviceStateWifiConfiguring:
                if (current_badge_layer_ != kBfWifi) ShowBadgeLayer(kBfWifi);
                UpdateHalo(COLOR_PEACH, 115, 204, 3000);   // 45 → 80 %
                SetDialMode(kDialOff);
                SetTickerText(AppVersionString());
                break;
            case kDeviceStateActivating:
                // Visually a continuation of boot — upstream xiaozhi exposes
                // 激活中 only as a status-text change, never as a separate
                // screen. We keep the bf-boot layer up so the OTA round-trip
                // doesn't flash a new screen at the user. SetEmotion("link")
                // (fired from ShowActivationCode) is the only thing that
                // promotes us to the bf-pairing layer.
                if (current_badge_layer_ != kBfPairing) {
                    ShowBadgeLayer(kBfBoot);
                }
                UpdateHalo(COLOR_PEACH, 115, 217, 2000);   // 45 → 85 %
                SetDialMode(kDialOff);
                SetTickerText(AppVersionString());
                break;
            case kDeviceStateConnecting:
                // Avatar layer only if we already have the user's image —
                // otherwise we'd flash the baked default while UserAvatarSync
                // is still downloading. The boot layer (with spinner) is the
                // honest "still preparing" surface.
                ShowBadgeLayer((user_avatar_ready_ || kLightweightBadgeUi) ? kBfAvatar : kBfBoot);
                UpdateHalo(COLOR_SAGE, 140, 255, 900);     // 55 → 100 %
                SetDialMode(kDialClock);
                SetTickerText("正在接通…");
                break;
            case kDeviceStateIdle:
            case kDeviceStateUnknown:
                ShowBadgeLayer((user_avatar_ready_ || kLightweightBadgeUi) ? kBfAvatar : kBfBoot);
                // Coral is our brand red, always-breathing — no gray ring.
                UpdateHalo(COLOR_CORAL, 51, 140, 5000);    // 20 → 55 %, slow & calm
                SetDialMode(kDialClock);
                SetTickerText(AppVersionString());
                break;
            case kDeviceStateListening:
                ShowBadgeLayer(kBfAvatar);
                UpdateHalo(COLOR_CORAL, 128, 230, 1600);   // 50 → 90 %, attentive
                SetDialMode(kDialClock);
                // When coming from Speaking (TTS just finished), let the
                // assistant's last sentence linger on the ticker so the user
                // has time to read it. SetChatMessage("user", text) on first
                // STT will replace. For other entry paths (idle/connecting/
                // unknown) show the "倾听中" placeholder.
                if (prev != kDeviceStateSpeaking) {
                    SetTickerText("倾听中");
                }
                break;
            case kDeviceStateSpeaking:
                ShowBadgeLayer(kBfAvatar);
                UpdateHalo(COLOR_CORAL, 178, 255, 1100);   // 70 → 100 %, vocal
                SetDialMode(kDialClock);
                // Don't reset the ticker — let the previous STT text linger
                // until the assistant's first sentence_start arrives via
                // SetChatMessage("assistant", ...). Avoids visible flicker
                // back to version line between user-speak and bot-speak.
                break;
            case kDeviceStateUpgrading:
                if (current_badge_layer_ != kBfUpgrading) ShowBadgeLayer(kBfUpgrading);
                UpdateHalo(COLOR_PEACH, 140, 242, 1400);   // 55 → 95 %
                SetDialMode(kDialProgress);
                break;
            case kDeviceStateAudioTesting:
                ShowBadgeLayer(kBfAvatar);
                UpdateHalo(COLOR_INK, 140, 255, 1600);
                SetDialMode(kDialOff);
                SetTickerText("音频测试中");
                break;
            case kDeviceStateFatalError:
            default:
                ShowBadgeLayer(kBfError);
                UpdateHalo(COLOR_RED, 153, 255, 700);
                SetDialMode(kDialOff);
                break;
        }

        // Low-battery overlay wins over normal halo color.
        if (low_battery_active_) {
            UpdateHalo(COLOR_RED, 102, 217, 2400);
            SetTickerText("电量不足，请尽快充电");
        }
    }
};

class CustomButton: public Button {
public:
    void OnPressDownDel(void) {
        if (button_handle_ == nullptr) {
            return;
        }
        on_press_down_ = NULL;
        iot_button_unregister_cb(button_handle_, BUTTON_PRESS_DOWN, nullptr);
    }
    void OnPressUpDel(void) {
        if (button_handle_ == nullptr) {
            return;
        }
        on_press_up_ = NULL;
        iot_button_unregister_cb(button_handle_, BUTTON_PRESS_UP, nullptr);
    }
};

class CustomBoard : public WifiBoard {
private:
    CustomButton boot_button_;
    CustomButton pwr_button_;
    i2c_master_bus_handle_t i2c_bus_;
    LcdDisplay* display_;
    PowerManager* power_manager_ = nullptr;
    PowerSaveTimer* power_save_timer_ = nullptr;

    void InitializePowerManager() {
        power_manager_ = new PowerManager(BATTERY_CHARGING_PIN, BATTERY_ADC_PIN, BATTERY_EN_PIN);
        power_manager_->PowerON();
    }

    void InitializePowerSaveTimer() {
        power_save_timer_ = new PowerSaveTimer(-1, 60, 300);
        power_save_timer_->OnEnterSleepMode([this]() {
            GetDisplay()->SetPowerSaveMode(true);
        });
        power_save_timer_->OnExitSleepMode([this]() {
            GetDisplay()->SetPowerSaveMode(false);
        });
        power_save_timer_->OnShutdownRequest([this]() {
            power_manager_->PowerOff();
        });
        power_save_timer_->SetEnabled(true);
    }

    void InitializeI2c() {
        // Initialize I2C peripheral
        i2c_master_bus_config_t i2c_bus_cfg = {
            .i2c_port = (i2c_port_t)I2C_NUM_0,
            .sda_io_num = AUDIO_CODEC_I2C_SDA_PIN,
            .scl_io_num = AUDIO_CODEC_I2C_SCL_PIN,
            .clk_source = I2C_CLK_SRC_DEFAULT,
            .glitch_ignore_cnt = 7,
            .intr_priority = 0,
            .trans_queue_depth = 0,
            .flags = {
                .enable_internal_pullup = 1,
            },
        };
        ESP_ERROR_CHECK(i2c_new_master_bus(&i2c_bus_cfg, &i2c_bus_));
    }
    
    void InitializeSpi() {
        ESP_LOGI(TAG, "Initialize QSPI bus");
        spi_bus_config_t buscfg = {};
        buscfg.mosi_io_num = DISPLAY_MOSI_PIN;
        buscfg.miso_io_num = DISPLAY_MISO_PIN;
        buscfg.sclk_io_num = DISPLAY_CLK_PIN;
        buscfg.quadwp_io_num = GPIO_NUM_NC;
        buscfg.quadhd_io_num = GPIO_NUM_NC;
        buscfg.max_transfer_sz = DISPLAY_WIDTH * DISPLAY_HEIGHT * sizeof(uint16_t);
        ESP_ERROR_CHECK(spi_bus_initialize(SPI2_HOST, &buscfg, SPI_DMA_CH_AUTO));
    }

    void InitializeLcdDisplay() {
        esp_lcd_panel_io_handle_t panel_io = nullptr;
        esp_lcd_panel_handle_t panel = nullptr;

        // 液晶屏控制IO初始化
        ESP_LOGI(TAG, "Install panel IO");
        esp_lcd_panel_io_spi_config_t io_config = {};
        io_config.cs_gpio_num = DISPLAY_CS_PIN;
        io_config.dc_gpio_num = DISPLAY_DC_PIN;
        io_config.spi_mode = DISPLAY_SPI_MODE;
        io_config.pclk_hz = 40 * 1000 * 1000;
        io_config.trans_queue_depth = 10;
        io_config.lcd_cmd_bits = 8;
        io_config.lcd_param_bits = 8;
        ESP_ERROR_CHECK(esp_lcd_new_panel_io_spi(SPI2_HOST, &io_config, &panel_io));

        // 初始化液晶屏驱动芯片
        ESP_LOGI(TAG, "Install LCD driver");
        esp_lcd_panel_dev_config_t panel_config = {};
        panel_config.reset_gpio_num = DISPLAY_RST_PIN;
        panel_config.rgb_ele_order = DISPLAY_RGB_ORDER;
        panel_config.bits_per_pixel = 16;
        ESP_ERROR_CHECK(esp_lcd_new_panel_st7789(panel_io, &panel_config, &panel)); 
        esp_lcd_panel_reset(panel);
        esp_lcd_panel_init(panel);
        esp_lcd_panel_invert_color(panel, DISPLAY_INVERT_COLOR);
        esp_lcd_panel_swap_xy(panel, DISPLAY_SWAP_XY);
        esp_lcd_panel_mirror(panel, DISPLAY_MIRROR_X, DISPLAY_MIRROR_Y);

        display_ = new CustomLcdDisplay(
            panel_io, 
            panel,
            DISPLAY_WIDTH, 
            DISPLAY_HEIGHT, 
            DISPLAY_OFFSET_X, 
            DISPLAY_OFFSET_Y, 
            DISPLAY_MIRROR_X, 
            DISPLAY_MIRROR_Y, 
            DISPLAY_SWAP_XY
        );
    }

    void InitializeButtons() {
        boot_button_.OnClick([this]() {
            auto& app = Application::GetInstance();
            if (app.GetDeviceState() == kDeviceStateStarting && !WifiStation::GetInstance().IsConnected()) {
                ResetWifiConfiguration();
            }
            app.ToggleChatState();
        });

        pwr_button_.OnPressUp([this]() {
            pwr_button_.OnDoubleClick([this]() {
                static uint8_t brightness_last = 0;
                auto backlight = Board::GetInstance().GetBacklight();
                if (backlight->brightness() == 0) {
                    brightness_last = 0;
                    if (brightness_last == 0) {
                        backlight->SetBrightness(50, true);
                    } else {
                        backlight->SetBrightness(brightness_last, true);
                    }
                } else {
                    brightness_last = backlight->brightness();
                    backlight->SetBrightness(0);
                }
            });

            pwr_button_.OnLongPress([this]() {
                // printf("Power button long press\n");
                if (power_manager_ != nullptr){
                    power_manager_->PowerOff();
                }
            });

            pwr_button_.OnPressUpDel();
        });
    }

public:
    CustomBoard() :
        boot_button_(BOOT_BUTTON_GPIO), pwr_button_(PWR_BUTTON_GPIO) {
        InitializePowerManager();
        InitializePowerSaveTimer();
        InitializeI2c();
        InitializeSpi();
        InitializeLcdDisplay();
        InitializeButtons();
        GetBacklight()->RestoreBrightness();
    }

    virtual AudioCodec* GetAudioCodec() override {
        static Es8311AudioCodec audio_codec(
            i2c_bus_, 
            I2C_NUM_0, 
            AUDIO_INPUT_SAMPLE_RATE, 
            AUDIO_OUTPUT_SAMPLE_RATE,
            AUDIO_I2S_GPIO_MCLK, 
            AUDIO_I2S_GPIO_BCLK, 
            AUDIO_I2S_GPIO_WS, 
            AUDIO_I2S_GPIO_DOUT, 
            AUDIO_I2S_GPIO_DIN,
            AUDIO_CODEC_PA_PIN, 
            AUDIO_CODEC_ES8311_ADDR
        );
        return &audio_codec;
    }

    virtual Display* GetDisplay() override {
        return display_;
    }
    
    virtual Backlight* GetBacklight() override {
        static PwmBacklight backlight(DISPLAY_BACKLIGHT_PIN, DISPLAY_BACKLIGHT_OUTPUT_INVERT);
        return &backlight;
    }

    virtual bool GetBatteryLevel(int &level, bool& charging, bool& discharging) override {
        static bool last_discharging = false;
        charging = power_manager_->IsCharging();
        discharging = power_manager_->IsDischarging();
        if (discharging != last_discharging) {
            power_save_timer_->SetEnabled(discharging);
            last_discharging = discharging;
        }
        level = power_manager_->GetBatteryLevel();
        return true;
    }

    virtual void SetPowerSaveMode(bool enabled) override {
        if (!enabled) {
            power_save_timer_->WakeUp();
        }
        WifiBoard::SetPowerSaveMode(enabled);
    }
};

DECLARE_BOARD(CustomBoard);
