#include "wifi_board.h"
#include "codecs/es8311_audio_codec.h"
#include "application.h"
#include "button.h"
#include "config.h"
#include "device_state_event.h"
#include "assets/lang_config.h"
#include "led/single_led.h"
#include "power_manager.h"
#include "power_save_timer.h"
#include <esp_log.h>
#include <esp_timer.h>
#include <driver/i2c_master.h>
#include <wifi_station.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

#define TAG "memomate_telephone"

// MemoMate Telephone — headless board (LCD removed) for a vintage rotary
// phone shell. Interaction model is deterministic by design after the IMU
// pickup-detection experiment proved too flaky in demos:
//   PWR  long-press → power on / off (battery EN soft-latch)
//   BOOT click      → talk key: start / pause conversation (ToggleChatState)
// State feedback with no screen: voice cues (below) + WS2812 LED colors
// (driven by the core via Led::OnStateChanged, zero code here).

// Ignore PWR long-press events in the first window after boot — on battery
// the MCU cold-starts because the user is physically pressing PWR, and we
// don't want a slightly-long boot tap to immediately trigger PowerOff.
static constexpr int64_t kBootLongPressGuardUs = 2'000'000;

class CustomBoard : public WifiBoard {
private:
    Button boot_button_;
    Button pwr_button_;
    i2c_master_bus_handle_t i2c_bus_;
    PowerManager* power_manager_ = nullptr;
    PowerSaveTimer* power_save_timer_ = nullptr;
    bool power_off_pending_ = false;

    void InitializePowerManager() {
        power_manager_ = new PowerManager(BATTERY_CHARGING_PIN, BATTERY_ADC_PIN, BATTERY_EN_PIN);
        power_manager_->PowerON();
    }

    void InitializePowerSaveTimer() {
        // No display to blank; sleep mode just lets the core throttle wake
        // word / audio input. 300 s idle on battery → auto power-off
        // (GetBatteryLevel below disables the timer while on USB).
        power_save_timer_ = new PowerSaveTimer(-1, 60, 300);
        power_save_timer_->OnShutdownRequest([this]() {
            PowerOffWithCue();
        });
        power_save_timer_->SetEnabled(true);
    }

    void InitializeI2c() {
        i2c_master_bus_config_t i2c_bus_cfg = {
            .i2c_port = (i2c_port_t)I2C_NUM_0,
            .sda_io_num = AUDIO_CODEC_I2C_SDA_PIN,
            .scl_io_num = AUDIO_CODEC_I2C_SCL_PIN,
            .clk_source = I2C_CLK_SRC_DEFAULT,
            .glitch_ignore_cnt = 7,
            .intr_priority = 0,
            .trans_queue_depth = 0,
            .flags = {
                .enable_internal_pullup = 1,
            },
        };
        ESP_ERROR_CHECK(i2c_new_master_bus(&i2c_bus_cfg, &i2c_bus_));
    }

    void InitializeButtons() {
        // BOOT = talk key. While still starting and unprovisioned it doubles
        // as the WiFi-config escape hatch (same as the other Hao Lab boards).
        boot_button_.OnClick([this]() {
            auto& app = Application::GetInstance();
            if (app.GetDeviceState() == kDeviceStateStarting && !WifiStation::GetInstance().IsConnected()) {
                ResetWifiConfiguration();
                return;
            }
            app.ToggleChatState();
        });

        // PWR long-press → power off. Registered directly in the ctor (not
        // deferred to the first press-up) so it also works on a USB-C cold
        // boot where the user never touched PWR; the boot guard rejects the
        // long-press generated by the very tap that cold-started the MCU.
        pwr_button_.OnLongPress([this]() {
            if (esp_timer_get_time() < kBootLongPressGuardUs) {
                ESP_LOGI(TAG, "PWR long-press within boot guard — ignored");
                return;
            }
            // While the button stays held the long-press event re-fires
            // about once per second — latch so we cue + power off once.
            if (power_off_pending_) {
                return;
            }
            power_off_pending_ = true;
            PowerOffWithCue();
        });
    }

    // Voice cues for state transitions the core doesn't already announce.
    // Core-provided sounds: boot-ready = success, wake word = popup,
    // wifi-config / activation / low-battery prompts are automatic.
    void InitializeStateCues() {
        DeviceStateEventManager::GetInstance().RegisterStateChangeCallback(
            [](DeviceState prev, DeviceState cur) {
                auto& app = Application::GetInstance();
                if (cur == kDeviceStateListening && prev == kDeviceStateIdle) {
                    // Talk key pressed, conversation starts (the wake-word
                    // path plays its own popup before the state flips, but a
                    // second cue on top is harmless and keeps this simple).
                    app.PlaySound(Lang::Sounds::OGG_POPUP);
                } else if (cur == kDeviceStateIdle &&
                           (prev == kDeviceStateListening || prev == kDeviceStateSpeaking)) {
                    // Conversation paused/ended.
                    app.PlaySound(Lang::Sounds::OGG_VIBRATION);
                }
            });
    }

    void PowerOffWithCue() {
        ESP_LOGI(TAG, "Power off requested");
        // Give the cue a moment to leave the speaker before cutting the
        // battery latch. On USB power the latch does nothing — the cue at
        // least tells the user the request registered.
        Application::GetInstance().PlaySound(Lang::Sounds::OGG_VIBRATION);
        vTaskDelay(pdMS_TO_TICKS(800));
        power_manager_->PowerOff();
        // Still running ⇒ USB keeps the rails up and the battery latch can't
        // cut us. Re-arm after a pause so a later battery-powered long-press
        // still works.
        vTaskDelay(pdMS_TO_TICKS(3000));
        power_off_pending_ = false;
        ESP_LOGI(TAG, "Still on USB power — PowerOff is a no-op, re-armed");
    }

public:
    CustomBoard() :
        boot_button_(BOOT_BUTTON_GPIO), pwr_button_(PWR_BUTTON_GPIO) {
        InitializePowerManager();
        InitializePowerSaveTimer();
        InitializeI2c();
        InitializeButtons();
        InitializeStateCues();
    }

    virtual AudioCodec* GetAudioCodec() override {
        static Es8311AudioCodec audio_codec(
            i2c_bus_,
            I2C_NUM_0,
            AUDIO_INPUT_SAMPLE_RATE,
            AUDIO_OUTPUT_SAMPLE_RATE,
            AUDIO_I2S_GPIO_MCLK,
            AUDIO_I2S_GPIO_BCLK,
            AUDIO_I2S_GPIO_WS,
            AUDIO_I2S_GPIO_DOUT,
            AUDIO_I2S_GPIO_DIN,
            AUDIO_CODEC_PA_PIN,
            AUDIO_CODEC_ES8311_ADDR,
            true,
            false,
            AUDIO_CODEC_PA_VOLTAGE
        );
        return &audio_codec;
    }

    virtual Led* GetLed() override {
        static SingleLed led(BUILTIN_LED_GPIO);
        return &led;
    }

    virtual bool GetBatteryLevel(int &level, bool& charging, bool& discharging) override {
        static bool last_discharging = false;
        charging = power_manager_->IsCharging();
        discharging = power_manager_->IsDischarging();
        if (discharging != last_discharging) {
            power_save_timer_->SetEnabled(discharging);
            last_discharging = discharging;
        }
        level = power_manager_->GetBatteryLevel();
        return true;
    }

    virtual void SetPowerSaveMode(bool enabled) override {
        if (!enabled) {
            power_save_timer_->WakeUp();
        }
        WifiBoard::SetPowerSaveMode(enabled);
    }
};

DECLARE_BOARD(CustomBoard);
